In [1]:
import pandas as pd    
dff=pd.read_csv('DF_COMPANIES_REDUZIDO.csv')
print(len(dff))

882

In [2]:
dff.columns

Index(['Unnamed: 0', 'url', 'Unnamed: 2', 'title', 'Unnamed: 4', 'text',
       'Unnamed: 6', 'empresa(s)', 'Unnamed: 8', 'pessoa(s)', 'Unnamed: 10',
       'fraude', 'Unnamed: 12', 'date_publication', 'empresas', 'pessoas'],
      dtype='str')

In [8]:
a= dff.loc[dff['title'].str.contains('Clima tenso: Ricardo Salles dispara contra Eduardo Bolsonaro e Valdemar da Costa Neto')]
dff=dff.drop(a.index) 
dff=dff.reset_index(drop=True)
print(len(dff))

881

In [9]:
dff.to_csv('DF_COMPANIES_REDUZIDO.csv', index=False)

In [3]:
import pandas as pd
df=pd.read_csv('NEGATIVE_DATASET_STRATIFIED.csv')
print(len(df))
print(df.columns)
print(df.head())

882
Index(['url', 'title', 'text', 'empresas', 'pessoas', 'fraude',
       'date_publication', 'source_file', 'category', 'portal', 'word_count',
       'label'],
      dtype='str')
                                                 url  \
0  https://jornalconexao.com.br/noticia/12489/mar...
1  https://jornalconexao.com.br/noticia/12460/rec...
2  https://jornalconexao.com.br/noticia/12477/tra...
3  https://jornalconexao.com.br/noticia/12475/gua...
4  https://jornalconexao.com.br/noticia/12485/mot...

                                               title  \
0  Mar revolto invade faixa de areia e assusta mo...
1  Reconexão emocional ganha espaço em vivência e...
2  Tragédia em escola no Acre: adolescente armado...
3  Guarda municipal de Florianópolis terá nova ca...
4  Motorista perde controle, cai com carro em rio...

                                                text  empresas  pessoas  \
0  A forteressacaregistrada no litoral catarinens...       NaN      NaN
1  Um convite ao reencontro interior marca a real...       NaN      NaN
2  Umadolescente de 13 anosprotagonizou um episód...       NaN      NaN
3  ACâmara Municipal de Florianópolisaprovou por ...       NaN      NaN
4  O sábado (10) terminou em tragédia no municípi...       NaN      NaN

   fraude date_publication                                        source_file  \
0     NaN       01/01/2024  Mar_revolto_invade_faixa_de_areia_e_assusta_mo...
1     NaN       01/01/2024  Reconexão_emocional_ganha_espaço_em_vivência_e...
2     NaN       01/01/2024  Tragédia_em_escola_no_Acre__adolescente_armado...
3     NaN       01/01/2024  Guarda_municipal_de_Florianópolis_terá_nova_ca...
4     NaN       01/01/2024  Motorista_perde_controle,_cai_com_carro_em_rio...

         category                portal  word_count     label
0  Hard Negatives  jornalconexao.com.br         238  negative
1  Hard Negatives  jornalconexao.com.br         278  negative
2  Hard Negatives  jornalconexao.com.br         252  negative
3  Hard Negatives  jornalconexao.com.br         223  negative
4  Pure Negatives  jornalconexao.com.br         218  negative

In [4]:
df.head()

,url,title,text,empresas,pessoas,fraude,date_publication,source_file,category,portal,word_count,label
0,https://jornalconexao.com.br/noticia/12489/mar...,Mar revolto invade faixa de areia e assusta mo...,A forteressacaregistrada no litoral catarinens...,NaN,NaN,NaN,01/01/2024,Mar_revolto_invade_faixa_de_areia_e_assusta_mo...,Hard Negatives,jornalconexao.com.br,238,negative
1,https://jornalconexao.com.br/noticia/12460/rec...,Reconexão emocional ganha espaço em vivência e...,Um convite ao reencontro interior marca a real...,NaN,NaN,NaN,01/01/2024,Reconexão_emocional_ganha_espaço_em_vivência_e...,Hard Negatives,jornalconexao.com.br,278,negative
2,https://jornalconexao.com.br/noticia/12477/tra...,Tragédia em escola no Acre: adolescente armado...,Umadolescente de 13 anosprotagonizou um episód...,NaN,NaN,NaN,01/01/2024,Tragédia_em_escola_no_Acre__adolescente_armado...,Hard Negatives,jornalconexao.com.br,252,negative
3,https://jornalconexao.com.br/noticia/12475/gua...,Guarda municipal de Florianópolis terá nova ca...,ACâmara Municipal de Florianópolisaprovou por ...,NaN,NaN,NaN,01/01/2024,Guarda_municipal_de_Florianópolis_terá_nova_ca...,Hard Negatives,jornalconexao.com.br,223,negative
4,https://jornalconexao.com.br/noticia/12485/mot...,"Motorista perde controle, cai com carro em rio...",O sábado (10) terminou em tragédia no municípi...,NaN,NaN,NaN,01/01/2024,"Motorista_perde_controle,_cai_com_carro_em_rio...",Pure Negatives,jornalconexao.com.br,218,negative

In [11]:
import pandas as pd
df=pd.read_csv('DF_COMPANIES_REDUZIDO.csv')
df.tail()

,Unnamed: 0,url,Unnamed: 2,title,Unnamed: 4,text,Unnamed: 6,empresa(s),Unnamed: 8,pessoa(s),Unnamed: 10,fraude,Unnamed: 12,date_publication
876,NaN,https://iclnoticias.com.br/deputado-alvo-busca...,NaN,Deputado estadual é alvo de buscas na Bahia po...,NaN,Por João Pedro Pitombo (Folhapress) – O deputa...,NaN,[],NaN,"['Pedro Pitombo', 'Adriano Lima', 'Assembleia ...",NaN,[],NaN,01/01/2024
877,NaN,https://www.bbc.com/portuguese/articles/c5y200...,NaN,Câmara rejeita cassação de Carla Zambelli apes...,NaN,"Crédito,Bruno Spada/Câmara dos Deputados A Câm...",NaN,[],NaN,"['Luiz Fux', 'Cristiano Zanin', 'Senado Moraes...",NaN,[],NaN,01/01/2024
878,NaN,https://www.bbc.com/portuguese/articles/c20vq0...,NaN,Como se saber se bebida está adulterada — e o...,NaN,"O ministro da Justiça e Segurança Pública, Ric...",NaN,[],NaN,"['Andrei Augusto Passos', 'Zona Leste', 'Sem F...",NaN,[],NaN,01/01/2024
879,NaN,https://www.cartacapital.com.br/politica/tre-d...,NaN,TRE de São Paulo cassa prefeito por abuso de p...,NaN,A decisão contra Antônio Carlos Camargo Ribas ...,NaN,[],NaN,"['Acompanharam Lagroiva', 'Roberto Maia', 'Tri...",NaN,[],NaN,01/01/2024
880,NaN,https://www.bbc.com/portuguese/articles/c4g98g...,NaN,'Nº 2 da Previdência' é preso: o que se sabe s...,NaN,"Crédito,Polícia Federal Uma nova fase da opera...",NaN,[],NaN,"['Carlos Lupi', 'Cunha Portal', 'Sem Desconto'...",NaN,[],NaN,01/01/2024

In [12]:
df2=pd.read_csv("/home/paulo/CascadeProjects/Applied_ML/dataset/DF_COMPANIES_ORIGINAL.csv")
df2.tail()

,Unnamed: 0,url,Unnamed: 2,title,Unnamed: 4,text,Unnamed: 6,empresa(s),Unnamed: 8,pessoa(s),Unnamed: 10,fraude,Unnamed: 12,date_publication
1045,NaN,https://www.nsctotal.com.br/noticias/toffoli-s...,NaN,Toffoli se afasta da relatoria do caso Master ...,NaN,Usuário\nMinha Conta\nSair\nRádios\nHome>DC>Po...,NaN,Banco Master; Maridte; BRB,NaN,Dias Toffoli (ministro); Edson Fachin (ministr...,NaN,fraude financeira,NaN,2026-02-12
1046,NaN,https://www.nsctotal.com.br/noticias/trump-pub...,NaN,Trump publica vídeo que mostra Michelle e Bara...,NaN,Usuário\nMinha Conta\nSair\nRádios\nHome>DC>Po...,NaN,Dominion Voting Systems,NaN,Donald Trump (presidente dos Estados Unidos); ...,NaN,fraude eleitoral,NaN,2026-02-06
1047,NaN,https://www.nsctotal.com.br/colunistas/estela-...,NaN,Uso de antigas ações do Besc nas fraudes do Ma...,NaN,Usuário\nMinha Conta\nSair\nRádios\nHome>Colun...,NaN,Banco do Estado de Santa Catarina (Besc); Banc...,NaN,NaN,NaN,fraude em valores mobiliários; fraude em fundos,NaN,2026-02-17
1048,NaN,https://www.nsctotal.com.br/colunistas/estela-...,NaN,Uso de antigas ações do Besc para fraude pelo ...,NaN,Usuário\nMinha Conta\nSair\nRádios\nHome>Colun...,NaN,Banco Master; Reag Trust; FIDC High Tower; Rea...,NaN,NaN,NaN,lavagem de dinheiro empresarial; fraude em tít...,NaN,2026-01-11
1049,NaN,https://www.nsctotal.com.br/noticias/veja-a-ma...,NaN,Veja a mansão de R$ 450 milhões em Miami ligad...,NaN,Usuário\nMinha Conta\nSair\nRádios\nHome>DC>Co...,NaN,Banco Master,NaN,Daniel Vorcaro (banker),NaN,fraude em títulos de crédito falsos; gestão fr...,NaN,2025-11-26