In [7]:
import pandas as pd
df = pd.read_csv('DF_COMPANIES_CLEAN.csv')
df.head(15)

,Unnamed: 0,url,Unnamed: 2,title,Unnamed: 4,text,Unnamed: 6,empresa(s),Unnamed: 8,pessoa(s),Unnamed: 10,fraude,Unnamed: 12,date_publication
0,NaN,https://www.mpsc.mp.br/noticias/em-irani-dois-...,NaN,"em irani, dois empresários denunciados pelo mp...",NaN,"em irani, dois empresários denunciados pelo mp...",NaN,"Grupo Crematório Catarinense, Bom Jesus, Grupo...",NaN,"Clésio Salvaro (prefeito de Criciúma), Felipe ...",NaN,"fraude em licitação, simulação de concorrência",NaN,NaN
1,NaN,https://www.mpsc.mp.br/noticias/ex-prefeito-de...,NaN,ex-prefeito de botuverá e mais quatro pessoas ...,NaN,ex-prefeito de botuverá e mais quatro pessoas ...,NaN,Triângulo Engenharia e Consultoria,NaN,"José Luiz Colombi (ex-prefeito), Fábio Maestri...",NaN,"fraude em licitação, direcionamento de licitaç...",NaN,NaN
2,NaN,https://omunicipio.com.br/ex-prefeito-de-botuv...,NaN,ex-prefeito de botuverá e outros seis são cond...,NaN,ex-prefeito de botuverá e outros seis são cond...,NaN,Tendas Catarinense Locações Ltda.,NaN,Edmilson Carlos Pereira Júnior (secretário mun...,NaN,"fraude em licitação, superfaturamento, falsifi...",NaN,NaN
3,NaN,https://pc.sc.gov.br/?p=18630,NaN,polícia civil realiza operação para investigar...,NaN,polícia civil realiza operação para investigar...,NaN,SAMEA,NaN,Gustavo Mereles Ruiz Diaz (promotor de justiça),NaN,"fraude em licitação, direcionamento de licitaç...",NaN,NaN
4,NaN,https://pc.sc.gov.br/?p=5310,NaN,polícia civil indicia quatro pessoas por crime...,NaN,polícia civil indicia quatro pessoas por crime...,NaN,Engetom Construção Civil Ltda.,NaN,"José Cláudio Gonçalves (prefeito), Valcir Antô...",NaN,"fraude em licitação, falsificação de documento...",NaN,NaN
5,NaN,https://g1.globo.com/sc/santa-catarina/noticia...,NaN,megaoperação contra fraude a licitações em pre...,NaN,megaoperação contra fraude a licitações em pre...,NaN,"Celk Sistemas, Educagenesis Ltda",NaN,"Júnior de Abreu Bento (prefeito de Garopaba), ...",NaN,"fraude em licitação, contratos fraudulentos",NaN,NaN
6,NaN,https://g1.globo.com/sc/santa-catarina/noticia...,NaN,prefeito reeleito em sc é afastado do cargo po...,NaN,prefeito reeleito em sc é afastado do cargo po...,NaN,Empresa Municipal de Água e Saneamento (EMASA)...,NaN,Douglas Costa Beber (ex-diretor da EMASA),NaN,"fraude em licitação, fraude em contratos, corr...",NaN,NaN
7,NaN,https://www.cnnbrasil.com.br/nacional/operacao...,NaN,operação combate esquema em licitações em sc,NaN,operação combate esquema em licitações em sc e...,NaN,Serrana Engenharia,NaN,"Ari Baglio (prefeito), Douglas Elias Costa (pr...",NaN,"fraude em licitação, falsidade ideológica, fal...",NaN,NaN
8,NaN,https://intranet.mpsc.mp.br/noticias/gaeco-e-g...,NaN,gaeco e geac deflagram segunda fase da operaçã...,NaN,gaeco e geac deflagram segunda fase da operaçã...,NaN,Dygi Comunicação Ltda.,NaN,Luísa Niencheski Calviera (promotora de justiça),NaN,"fraude em licitações, desvio de recursos públicos",NaN,NaN
9,NaN,https://www.mpsc.mp.br/noticias/gaeco-deflagra...,NaN,"gaeco deflagra operação ""lata velha""",NaN,"gaeco deflagra operação ""lata velha""\nno total...",NaN,Veigamed,NaN,Jones Bósio (ex-secretário de desenvolvimento ...,NaN,fraude em licitação,NaN,NaN
10,NaN,https://portal.mpsc.mp.br/noticias/ex-secretar...,NaN,ex-secretário de desenvolvimento regional de b...,NaN,ex-secretário de desenvolvimento regional de b...,NaN,Veigamed,NaN,Roberto Biava (prefeito),NaN,"fraude em licitação, simulação de licitação, f...",NaN,NaN
11,NaN,https://www.nsctotal.com.br/noticias/fraude-em...,NaN,fraude em licitações gera megaoperação em 22 c...,NaN,fraude em licitações gera megaoperação em 22 c...,NaN,"Celk Sistemas, NSC TV",NaN,"Anderson Silva (informante), Ana Cristina Mach...",NaN,"fraude em licitação, lavagem de dinheiro",NaN,NaN
12,NaN,https://www.tcesc.tc.br/informacoes-do-tcesc-e...,NaN,"por fraude em licitação, agente público e empr...",NaN,"por fraude em licitação, agente público e empr...",NaN,"empresa ""laranja, empresa ligada ao ramo de ma...",NaN,José Cláudio Gonçalves (prefeito),NaN,"fraude em licitação, desvio de finalidade, pag...",NaN,NaN
13,NaN,https://lerunica.com.br/amurel/empresarios-e-f...,NaN,gaeco cumpre nove mandados de busca e apreensã...,NaN,gaeco cumpre nove mandados de busca e apreensã...,NaN,"risotolândia, g.e.f. serviços ltda.",NaN,Marcionei Mendes (promotor de justiça),NaN,"fraude em licitação, contratos fraudulentos, d...",NaN,NaN
14,NaN,https://www.mpsc.mp.br/noticias/recebida-denun...,NaN,gaeco deflagra operação verus dominus na comar...,NaN,gaeco deflagra operação verus dominus na comar...,NaN,"Veigamed, mmj, je comérico, RTS Rio S/A",NaN,"Andrey Cunha Amorim (promotor de justiça), Isa...",NaN,"fraude em licitações, sobrepreço, desvio de re...",NaN,NaN

In [4]:
print(df.loc[8])

Unnamed: 0                                                        NaN
url                 https://intranet.mpsc.mp.br/noticias/gaeco-e-g...
Unnamed: 2                                                        NaN
title               gaeco e geac deflagram segunda fase da operaçã...
Unnamed: 4                                                        NaN
text                gaeco e geac deflagram segunda fase da operaçã...
Unnamed: 6                                                        NaN
empresa(s)                                     Dygi Comunicação Ltda.
Unnamed: 8                                                        NaN
pessoa(s)            Luísa Niencheski Calviera (promotora de justiça)
Unnamed: 10                                                       NaN
fraude              fraude em licitações, desvio de recursos públicos
Unnamed: 12                                                       NaN
date_publication                                                  NaN
Name: 8, dtype: object

In [12]:
df=df.drop(index=8)
df=df.reset_index(drop=True)
df.head(15)

,Unnamed: 0,url,Unnamed: 2,title,Unnamed: 4,text,Unnamed: 6,empresa(s),Unnamed: 8,pessoa(s),Unnamed: 10,fraude,Unnamed: 12,date_publication
0,NaN,https://www.mpsc.mp.br/noticias/em-irani-dois-...,NaN,"em irani, dois empresários denunciados pelo mp...",NaN,"em irani, dois empresários denunciados pelo mp...",NaN,"Grupo Crematório Catarinense, Bom Jesus, Grupo...",NaN,"Clésio Salvaro (prefeito de Criciúma), Felipe ...",NaN,"fraude em licitação, simulação de concorrência",NaN,NaN
1,NaN,https://www.mpsc.mp.br/noticias/ex-prefeito-de...,NaN,ex-prefeito de botuverá e mais quatro pessoas ...,NaN,ex-prefeito de botuverá e mais quatro pessoas ...,NaN,Triângulo Engenharia e Consultoria,NaN,"José Luiz Colombi (ex-prefeito), Fábio Maestri...",NaN,"fraude em licitação, direcionamento de licitaç...",NaN,NaN
2,NaN,https://omunicipio.com.br/ex-prefeito-de-botuv...,NaN,ex-prefeito de botuverá e outros seis são cond...,NaN,ex-prefeito de botuverá e outros seis são cond...,NaN,Tendas Catarinense Locações Ltda.,NaN,Edmilson Carlos Pereira Júnior (secretário mun...,NaN,"fraude em licitação, superfaturamento, falsifi...",NaN,NaN
3,NaN,https://pc.sc.gov.br/?p=18630,NaN,polícia civil realiza operação para investigar...,NaN,polícia civil realiza operação para investigar...,NaN,SAMEA,NaN,Gustavo Mereles Ruiz Diaz (promotor de justiça),NaN,"fraude em licitação, direcionamento de licitaç...",NaN,NaN
4,NaN,https://pc.sc.gov.br/?p=5310,NaN,polícia civil indicia quatro pessoas por crime...,NaN,polícia civil indicia quatro pessoas por crime...,NaN,Engetom Construção Civil Ltda.,NaN,"José Cláudio Gonçalves (prefeito), Valcir Antô...",NaN,"fraude em licitação, falsificação de documento...",NaN,NaN
5,NaN,https://g1.globo.com/sc/santa-catarina/noticia...,NaN,megaoperação contra fraude a licitações em pre...,NaN,megaoperação contra fraude a licitações em pre...,NaN,"Celk Sistemas, Educagenesis Ltda",NaN,"Júnior de Abreu Bento (prefeito de Garopaba), ...",NaN,"fraude em licitação, contratos fraudulentos",NaN,NaN
6,NaN,https://g1.globo.com/sc/santa-catarina/noticia...,NaN,prefeito reeleito em sc é afastado do cargo po...,NaN,prefeito reeleito em sc é afastado do cargo po...,NaN,Empresa Municipal de Água e Saneamento (EMASA)...,NaN,Douglas Costa Beber (ex-diretor da EMASA),NaN,"fraude em licitação, fraude em contratos, corr...",NaN,NaN
7,NaN,https://www.cnnbrasil.com.br/nacional/operacao...,NaN,operação combate esquema em licitações em sc,NaN,operação combate esquema em licitações em sc e...,NaN,Serrana Engenharia,NaN,"Ari Baglio (prefeito), Douglas Elias Costa (pr...",NaN,"fraude em licitação, falsidade ideológica, fal...",NaN,NaN
8,NaN,https://intranet.mpsc.mp.br/noticias/gaeco-e-g...,NaN,gaeco e geac deflagram segunda fase da operaçã...,NaN,gaeco e geac deflagram segunda fase da operaçã...,NaN,Dygi Comunicação Ltda.,NaN,Luísa Niencheski Calviera (promotora de justiça),NaN,"fraude em licitações, desvio de recursos públicos",NaN,NaN
9,NaN,https://www.mpsc.mp.br/noticias/gaeco-deflagra...,NaN,"gaeco deflagra operação ""lata velha""",NaN,"gaeco deflagra operação ""lata velha""\nno total...",NaN,Veigamed,NaN,Jones Bósio (ex-secretário de desenvolvimento ...,NaN,fraude em licitação,NaN,NaN
10,NaN,https://portal.mpsc.mp.br/noticias/ex-secretar...,NaN,ex-secretário de desenvolvimento regional de b...,NaN,ex-secretário de desenvolvimento regional de b...,NaN,Veigamed,NaN,Roberto Biava (prefeito),NaN,"fraude em licitação, simulação de licitação, f...",NaN,NaN
11,NaN,https://www.nsctotal.com.br/noticias/fraude-em...,NaN,fraude em licitações gera megaoperação em 22 c...,NaN,fraude em licitações gera megaoperação em 22 c...,NaN,"Celk Sistemas, NSC TV",NaN,"Anderson Silva (informante), Ana Cristina Mach...",NaN,"fraude em licitação, lavagem de dinheiro",NaN,NaN
12,NaN,https://www.tcesc.tc.br/informacoes-do-tcesc-e...,NaN,"por fraude em licitação, agente público e empr...",NaN,"por fraude em licitação, agente público e empr...",NaN,"empresa ""laranja, empresa ligada ao ramo de ma...",NaN,José Cláudio Gonçalves (prefeito),NaN,"fraude em licitação, desvio de finalidade, pag...",NaN,NaN
13,NaN,https://lerunica.com.br/amurel/empresarios-e-f...,NaN,gaeco cumpre nove mandados de busca e apreensã...,NaN,gaeco cumpre nove mandados de busca e apreensã...,NaN,"risotolândia, g.e.f. serviços ltda.",NaN,Marcionei Mendes (promotor de justiça),NaN,"fraude em licitação, contratos fraudulentos, d...",NaN,NaN
14,NaN,https://www.mpsc.mp.br/noticias/recebida-denun...,NaN,gaeco deflagra operação verus dominus na comar...,NaN,gaeco deflagra operação verus dominus na comar...,NaN,"Veigamed, mmj, je comérico, RTS Rio S/A",NaN,"Andrey Cunha Amorim (promotor de justiça), Isa...",NaN,"fraude em licitações, sobrepreço, desvio de re...",NaN,NaN

In [9]:
print(df.shape)

(1050, 14)

In [12]:
df.columns

Index(['url', 'title', 'text', 'empresa(s)', 'pessoa(s)', 'fraude',
       'date_publication'],
      dtype='str')

In [ ]:
df=df.drop(columns=['Unnamed: 0', 'Unnamed: 2', 'Unnamed: 4', 'Unnamed: 6', 'Unnamed: 8', 'Unnamed: 10', 'Unnamed: 12'])

In [14]:
df.head(15)

,url,title,text,empresa(s),pessoa(s),fraude,date_publication
0,https://www.mpsc.mp.br/noticias/em-irani-dois-...,"em irani, dois empresários denunciados pelo mp...","em irani, dois empresários denunciados pelo mp...","Grupo Crematório Catarinense, Bom Jesus, Grupo...","Clésio Salvaro (prefeito de Criciúma), Felipe ...","fraude em licitação, simulação de concorrência",NaN
1,https://www.mpsc.mp.br/noticias/ex-prefeito-de...,ex-prefeito de botuverá e mais quatro pessoas ...,ex-prefeito de botuverá e mais quatro pessoas ...,Triângulo Engenharia e Consultoria,"José Luiz Colombi (ex-prefeito), Fábio Maestri...","fraude em licitação, direcionamento de licitaç...",NaN
2,https://omunicipio.com.br/ex-prefeito-de-botuv...,ex-prefeito de botuverá e outros seis são cond...,ex-prefeito de botuverá e outros seis são cond...,Tendas Catarinense Locações Ltda.,Edmilson Carlos Pereira Júnior (secretário mun...,"fraude em licitação, superfaturamento, falsifi...",NaN
3,https://pc.sc.gov.br/?p=18630,polícia civil realiza operação para investigar...,polícia civil realiza operação para investigar...,SAMEA,Gustavo Mereles Ruiz Diaz (promotor de justiça),"fraude em licitação, direcionamento de licitaç...",NaN
4,https://pc.sc.gov.br/?p=5310,polícia civil indicia quatro pessoas por crime...,polícia civil indicia quatro pessoas por crime...,Engetom Construção Civil Ltda.,"José Cláudio Gonçalves (prefeito), Valcir Antô...","fraude em licitação, falsificação de documento...",NaN
5,https://g1.globo.com/sc/santa-catarina/noticia...,megaoperação contra fraude a licitações em pre...,megaoperação contra fraude a licitações em pre...,"Celk Sistemas, Educagenesis Ltda","Júnior de Abreu Bento (prefeito de Garopaba), ...","fraude em licitação, contratos fraudulentos",NaN
6,https://g1.globo.com/sc/santa-catarina/noticia...,prefeito reeleito em sc é afastado do cargo po...,prefeito reeleito em sc é afastado do cargo po...,Empresa Municipal de Água e Saneamento (EMASA)...,Douglas Costa Beber (ex-diretor da EMASA),"fraude em licitação, fraude em contratos, corr...",NaN
7,https://www.cnnbrasil.com.br/nacional/operacao...,operação combate esquema em licitações em sc,operação combate esquema em licitações em sc e...,Serrana Engenharia,"Ari Baglio (prefeito), Douglas Elias Costa (pr...","fraude em licitação, falsidade ideológica, fal...",NaN
8,https://intranet.mpsc.mp.br/noticias/gaeco-e-g...,gaeco e geac deflagram segunda fase da operaçã...,gaeco e geac deflagram segunda fase da operaçã...,Dygi Comunicação Ltda.,Luísa Niencheski Calviera (promotora de justiça),"fraude em licitações, desvio de recursos públicos",NaN
9,https://www.mpsc.mp.br/noticias/gaeco-deflagra...,"gaeco deflagra operação ""lata velha""","gaeco deflagra operação ""lata velha""\nno total...",Veigamed,Jones Bósio (ex-secretário de desenvolvimento ...,fraude em licitação,NaN
10,https://portal.mpsc.mp.br/noticias/ex-secretar...,ex-secretário de desenvolvimento regional de b...,ex-secretário de desenvolvimento regional de b...,Veigamed,Roberto Biava (prefeito),"fraude em licitação, simulação de licitação, f...",NaN
11,https://www.nsctotal.com.br/noticias/fraude-em...,fraude em licitações gera megaoperação em 22 c...,fraude em licitações gera megaoperação em 22 c...,"Celk Sistemas, NSC TV","Anderson Silva (informante), Ana Cristina Mach...","fraude em licitação, lavagem de dinheiro",NaN
12,https://www.tcesc.tc.br/informacoes-do-tcesc-e...,"por fraude em licitação, agente público e empr...","por fraude em licitação, agente público e empr...","empresa ""laranja, empresa ligada ao ramo de ma...",José Cláudio Gonçalves (prefeito),"fraude em licitação, desvio de finalidade, pag...",NaN
13,https://lerunica.com.br/amurel/empresarios-e-f...,gaeco cumpre nove mandados de busca e apreensã...,gaeco cumpre nove mandados de busca e apreensã...,"risotolândia, g.e.f. serviços ltda.",Marcionei Mendes (promotor de justiça),"fraude em licitação, contratos fraudulentos, d...",NaN
14,https://www.mpsc.mp.br/noticias/recebida-denun...,gaeco deflagra operação verus dominus na comar...,gaeco deflagra operação verus dominus na comar...,"Veigamed, mmj, je comérico, RTS Rio S/A","Andrey Cunha Amorim (promotor de justiça), Isa...","fraude em licitações, sobrepreço, desvio de re...",NaN